language: java

jdk:
  - oraclejdk8
  
before_install:
# nothing

install: 
  - mvn validate -V
  
script:
  - mvn install -V -B
  - mvn failsafe:integration-test failsafe:verify -V -B
  
after_script:
# nothing
 
